// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj78-ykWA_rJrrlesqzwQv_LZ9IAOEfWk',
    appId: '1:426887760801:web:9f5ef250a4486e082759e0',
    messagingSenderId: '426887760801',
    projectId: 'instagram-clone-19b89',
    authDomain: 'instagram-clone-19b89.firebaseapp.com',
    storageBucket: 'instagram-clone-19b89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb12HNg5oY-S6OrSyhiJDTXgCWYpBhRSs',
    appId: '1:426887760801:android:926b4c6450ca8d562759e0',
    messagingSenderId: '426887760801',
    projectId: 'instagram-clone-19b89',
    storageBucket: 'instagram-clone-19b89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAogwuZW1QHLOTYDm7U3_X4d_ZdIS2_UYM',
    appId: '1:426887760801:ios:dfa9cca1322376212759e0',
    messagingSenderId: '426887760801',
    projectId: 'instagram-clone-19b89',
    storageBucket: 'instagram-clone-19b89.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAogwuZW1QHLOTYDm7U3_X4d_ZdIS2_UYM',
    appId: '1:426887760801:ios:d593ec67632eef612759e0',
    messagingSenderId: '426887760801',
    projectId: 'instagram-clone-19b89',
    storageBucket: 'instagram-clone-19b89.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
